export const mockedOperationsData = [
   {
      id: 1,
      param1: 'EG234-78',
      param2: 'Зачистити кут',
      param3: '47%',
   }, {
      id: 2,
      param1: 'EG234-78',
      param2: 'Зачистити кут',
      param3: '47%',
   },
   {
      id: 3,
      param1: 'EG234-78',
      param2: 'Зачистити кут',
      param3: '47%',
   },
   {
      id: 4,
      param1: 'EG234-78',
      param2: 'Зачистити кут',
      param3: '47%',
   },
   {
      id: 5,
      param1: 'EG234-78',
      param2: 'Зачистити кут',
      param3: '47%',
   },
   {
      id: 6,
      param1: 'EG234-78',
      param2: 'Зачистити кут',
      param3: '47%',
   },
]

export const mockedDetailsData = [
   {
      id: 1,
      name: 'Боковина',
      material: 'EG2800*2070*18 мм H1615 ST9 Вишня Верона',
      product: 'Т.в. котел',
      thickness: 18,
      length: 1085,
      width: 340,
      topLength: 'EGABS 23*08 мм U216 ST9',
      bottomLength: 'EGABS 23*08 мм U216 ST9',
      rightWidth: 'EGABS 23*08 мм U216 ST9',
      leftWidth: 'EGABS 23*08 мм U216 ST9',
      path: '',
      drilling: '',
      milling: '',
      desc: 'фрез пі ручку',
      amount: '1',
      status: 'В роботі'
   }, {
      id: 2,
      name: 'Боковина',
      material: 'EG2800*2070*18 мм H1615 ST9 Вишня Верона',
      product: 'Т.в. котел',
      thickness: 18,
      length: 1085,
      width: 340,
      topLength: 'EGABS 23*08 мм U216 ST9',
      bottomLength: 'EGABS 23*08 мм U216 ST9',
      rightWidth: 'EGABS 23*08 мм U216 ST9',
      leftWidth: 'EGABS 23*08 мм U216 ST9',
      path: '',
      drilling: '',
      milling: '',
      desc: 'фрез пі ручку',
      amount: 1,
      status: 'В роботі'
   }, {
      id: 3,
      name: 'Боковина',
      material: 'EG2800*2070*18 мм H1615 ST9 Вишня Верона',
      product: 'Т.в. котел',
      thickness: 18,
      length: 1085,
      width: 340,
      topLength: 'EGABS 23*08 мм U216 ST9',
      bottomLength: 'EGABS 23*08 мм U216 ST9',
      rightWidth: 'EGABS 23*08 мм U216 ST9',
      leftWidth: 'EGABS 23*08 мм U216 ST9',
      path: '',
      drilling: '',
      milling: '',
      desc: 'фрез пі ручку',
      amount: 1,
      status: 'В роботі'
   }, {
      id: 4,
      name: 'Боковина',
      material: 'EG2800*2070*18 мм H1615 ST9 Вишня Верона',
      product: 'Т.в. котел',
      thickness: 18,
      length: 1085,
      width: 340,
      topLength: 'EGABS 23*08 мм U216 ST9',
      bottomLength: 'EGABS 23*08 мм U216 ST9',
      rightWidth: 'EGABS 23*08 мм U216 ST9',
      leftWidth: 'EGABS 23*08 мм U216 ST9',
      path: '',
      drilling: '',
      milling: '',
      desc: 'фрез пі ручку',
      amount: 1,
      status: 'В роботі'
   }, {
      id: 5,
      name: 'Боковина',
      material: 'EG2800*2070*18 мм H1615 ST9 Вишня Верона',
      product: 'Т.в. котел',
      thickness: 18,
      length: 1085,
      width: 340,
      topLength: 'EGABS 23*08 мм U216 ST9',
      bottomLength: 'EGABS 23*08 мм U216 ST9',
      rightWidth: 'EGABS 23*08 мм U216 ST9',
      leftWidth: 'EGABS 23*08 мм U216 ST9',
      path: '',
      drilling: '',
      milling: '',
      desc: 'фрез пі ручку',
      amount: 1,
      status: 'В роботі'
   },
   {
      id: 6,
      name: 'Боковина',
      material: 'EG2800*2070*18 мм H1615 ST9 Вишня Верона',
      product: 'Т.в. котел',
      thickness: 18,
      length: 1085,
      width: 340,
      topLength: 'EGABS 23*08 мм U216 ST9',
      bottomLength: 'EGABS 23*08 мм U216 ST9',
      rightWidth: 'EGABS 23*08 мм U216 ST9',
      leftWidth: 'EGABS 23*08 мм U216 ST9',
      path: '',
      drilling: '',
      milling: '',
      desc: 'фрез пі ручку',
      amount: 1,
      status: 'В роботі'
   }, {
      id: 7,
      name: 'Боковина',
      material: 'EG2800*2070*18 мм H1615 ST9 Вишня Верона',
      product: 'Т.в. котел',
      thickness: 18,
      length: 1085,
      width: 340,
      topLength: 'EGABS 23*08 мм U216 ST9',
      bottomLength: 'EGABS 23*08 мм U216 ST9',
      rightWidth: 'EGABS 23*08 мм U216 ST9',
      leftWidth: 'EGABS 23*08 мм U216 ST9',
      path: '',
      drilling: '',
      milling: '',
      desc: 'фрез пі ручку',
      amount: 1,
      status: 'В роботі'
   },

]

export const mockedImageArray = [
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
   'https://picsum.photos/200/300',
]

export const mockedComplectationsData = [
   {
      id: 1,
      param1: 'https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg',
      param2: 'Тумба',
      param3: '4',
      param4: '7',
   }, {
      id: 2,
      param1: 'https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg',
      param2: 'Тумба',
      param3: '4',
      param4: '7',
   },
   {
      id: 3,
      param1: 'https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg',
      param2: 'Тумба',
      param3: '4',
      param4: '7',
   },
   {
      id: 4,
      param1: 'https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg',
      param2: 'Тумба',
      param3: '4',
      param4: '7',
   },
   {
      id: 5,
      param1: 'https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg',
      param2: 'Тумба',
      param3: '4',
      param4: '7',
   },
]

export const imageUrls = [
   "https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg",
   "https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg",
   "https://raw.githubusercontent.com/dolanmiu/docx/master/demo/images/cat.jpg",
];